spring:
  data:
    mongodb:
      username: admin123
      password: admin123
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
